### ISSUE TITLE
Library List Suggestions

### ISSUE THREAD

**Issue by bvstone** [WorksOfBarry/ILEditor#27]
Liam, first let me say how impressed I am with this editor!  Nice job!

In using it for a little bit here are a couple issues I have:

1.  Library list - If we select "Use User Profile Library List" it would be nice if it loaded the library list into the screen so we can verify and/or edit this library list.  Also if it set the current library to the user profile's current library.  Maybe a button (Load User Library List) instead of a checkbox?

2.  A default Current Library setting for new systems?  I don't think I've ever used SYSTOOLS.

3.  When firing up the editor, does it always need to be maximized.  A small thing, I know.  :)

Again, that's for your hard work!

**Comment by worksofliam** [comment]
Hi @bvstone 

Thanks for the kind comments.

1. Will be implemented. I won't keep a deadline, but I will get it into the library list tool.

2. I just stuck SYSTOOLS in there because... not sure actually! I will make it use the users library list when I have implemented that functionality.

3. Not sure why you wouldn't want it in full screen. Can this be justified?

Many thanks,
Liam

**Comment by bvstone** [comment]
Normally windows return to the size they were closed at when reopening.
Not a huge deal, just something annoying.  I use 2 27" monitors so full
screen is overwhelming.

**Comment by getfoundational** [comment]
I would concur with Brad on the window size retention.  I normally have the code on half my screen and something else (XML, JSON, EDI) on the other side that I am referencing as part of the code I am writing.
