### ISSUE TITLE
UI changes

### ISSUE THREAD

**Issue by fallingrock** [WorksOfBarry/ILEditor#67]
A few UI suggestions ...

- [x] On the connection settings panels, instead of "FTPES"  use "FTP SSL". Personally, I've never hard of "FTPES".
- [ ] For source pf input fields, use "SRC PF" as the tool tip instead of "SPF".
- [x] On the ILEditor tab of the connection settings, change the label "Executable" to "ACS executable" or (even better) don't require an executable and let the user point to the JAR file.
- [x] Don't make the connection settings dialog float on top of all other dialogs.
- [ ] If the toolbox pane is open, and the user selects Tools / Open Toolbox, don't open another toolbox pane.

**Comment by worksofliam** [comment]
I have made three commits this morning which fix three of the ticked issues. I will get around to changing the "SPF" to "SRC PF" issue long term.

**Comment by Krishrt** [comment]
Hi  @worksofliam #67 The ticked part which referring to pointing JAR files instead of EXE is still out there. 

- [ ] ![Applications-exe](https://user-images.githubusercontent.com/36916414/62638837-ee23d900-b95b-11e9-81a3-bdf0b30f2be9.PNG)

![FindACS](https://user-images.githubusercontent.com/36916414/62638862-f8de6e00-b95b-11e9-82de-32e3272837d5.PNG)
