### ISSUE TITLE
Setup program name

### ISSUE THREAD

**Issue by fallingrock** [WorksOfBarry/ILEditor#68]
Kind of a minor annoyance ... but it would be better if the setup program name was meaningful instead of generic.

Instead of "setup.exe", make it "ileeditor-setup.exe".

**Comment by worksofliam** [comment]
It's possible that in the next major release we could change the installer name, but it's very unlikely to happen anytime soon.

**Comment by worksofliam** [comment]
Now this is possible, but since I am using Visual Studio to automate the deployment right onto the server. This means I cannot rename the installer until it has reached the server, and then it I will have to manually do it anyway - this also means I would have to update the website. There is not a lot of benifit in doing this, so I will close for now.
