### ISSUE TITLE
Application terminates abruptly

### ISSUE THREAD

**Issue by Sumeel** [WorksOfBarry/ILEditor#71]
Hi Liam,

When I have test source and production source opened in two different tabs and unknowingly I update and save the production source(for which I do not have authority),instead of showing the warning/error message ,application is getting terminated abruptly.Need help on this.

**Comment by worksofliam** [comment]
Hi @Sumeel 

Can you please give me steps in numeric order so I can try and recreate on my machine.

Thanks,
Liam

**Comment by Sumeel** [comment]
Hi Liam,

Please find my comment as below.

1.In one of the tabs, I was working on Test Source(which was in my library).
2.Opened the same source from the production library in another tab.
3. I did some changes in the test source but not saved.
4.Unknowingly I added another few lines in production source (instead of test source) and tried to save the production source .(for which I do not have authority).
5.Application got struck for sometime and got terminated and all the changes done are lost.

**Comment by worksofliam** [comment]
Hi @Sumeel 

Sorry I haven't been able to help much. You haven't updated the issue since you posted your steps, so if you continue to have issues please feel free to re-open. If it's priority, please recreate the steps - and before you think it's going to crash please grab a copy of the Session FTP Log (Help -> Session FTP Log) and paste it here.

Thanks!
Liam
