### ISSUE TITLE
Login port other than 21

### ISSUE THREAD

**Issue by bluezdood** [WorksOfBarry/ILEditor#78]
Currently trying version 1.6.0.1 and we can't get the port option to work. Tried multiple formats, no such luck.

![error](https://user-images.githubusercontent.com/36970400/39877680-14c2e544-5466-11e8-9d05-46f8363d0c54.jpg)

**Comment by worksofliam** [comment]
Hi @bluezdood

I am travelling at the moment but when I am able to I will take a look at this.

Thanks!

**Comment by worksofliam** [comment]
Hi! The bug is fixed. Looks like when I added the ability I didn't test it very well.

742eff410b6405a2644bca0226cdf050df63d686

This will be out in the next release (no idea when that is at the moment, I'd say a week or two)

I will close this issue, but you should re-open if it the fix does not work.

Thanks,
Liam
