### ISSUE TITLE
Using VS Code

### ISSUE THREAD

**Issue by ramstein74** [WorksOfBarry/ILEditor#98]
Liking your editor so far but have you considered using vs code instead of creating an editor from scratch and just adding a plugin to connect and browse iseries ??
Maybe it would cut a lot of development time reinventing what is already available...
Regards

**Comment by worksofliam** [comment]
Hey @ramstein74 

Yes - before ILEditor was a thing I was writing extensions for not only VSCode, but also Visual Studio.

VSCode is a great fit until it comes to working with source members and compiling remotely, which is why I just built something from the ground up to work the way I wanted.

ILEditor is over a year old now and is more stable than ever.

Thanks,
Liam Barry
